server:
  port: 8020
spring:
  application:
    name: service-product
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848 # nacos 地址
      discovery:
        username: nacos
        password: nacos
        namespace: public
        ephemeral: false
        group: DEV