server:
  port: 8010
spring:
  application:
    name: service-order
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848 # nacos 地址
      discovery:
        username: nacos
        password: nacos
        namespace: public
        group: DEV
service-product:
  ribbon:
    NFLoadBalancerRuleClassName: loadbalance.MyRandomRule
ribbon:
  eager-load:
    enabled: true
    clients: service-product, service-stock
